"""add password to users

Revision ID: 866769c6d55b
Revises: 24c5acbaff99
Create Date: 2026-01-19 11:38:23.940034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '866769c6d55b'
down_revision: Union[str, Sequence[str], None] = '24c5acbaff99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Password column already created in initial migration
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Password column managed by initial migration
    pass
    # ### end Alembic commands ###
